#!/bin/bash

	# ================================================================================
	# Program:	extract_pkglist
	#
	# Purpose:	Extract the line between two tag lines.
	#
	# Author:	old giza
	#
	# Date:		2018.07.18
	#
	#			This can probably be done better with awk or the like.
	#			But it serves the purpose now.
	#			Which is to simply look for three consecutive lines like:
	#				<tag>
	#				line
	#				</tag>
	#			and extract the middle line. The "tag" can be anything. It should
	#			be supplied to the program as an argument. The program assumes the tags
	#			are isolated on lines of their own, and there is only one intervening
	#			data line.
	#
	#			This program is used to extract categories and descriptions from
	#			.pm files used by mx-packageinstaller in the directory
	#			/usr/share/mx-packageinstaller-pkglist. Note that there are other
	#			non .pm types of files in that directory.
	# ================================================================================

if [ -z "$1" ]
then	echo 'Need tag as argument (do not include < or />'
		exit
fi

tag="$1"
l1tag='<'"$tag"'>'
l3tag='</'"$tag"'>'

outfile="$tag"'.extract'
echo -n > "$outfile"

d='mx-packageinstaller-pkglist'

for f in $(ls -1 "$d"/*'.pm')
do

	let l1found=0
	let l2found=0
	let l3found=0

	while read l
	do
		if [ $l1found -eq 0 ]
			then	if [ "$l" = "$l1tag" ]
					then	let l1found=1
					fi
		else	if [ $l2found -eq 0 ]
				then	t="$l"
						let l2found=1
				else	if [ $l3found -eq 0 ]
						then	if [ "$l" != "$l3tag" ]
								then	echo 'file: '"$f"' - not 3 consecutive lines'
										exit
								else	let l3found=1
								fi
						fi
				fi
		fi
					
	done < "$f"

	let total=l1found+l2found+l3found
	if [ $total -ne 3 ]
	then	echo 'file: '"$f"' - did not find expected lines'
	else	echo "$t" >> "$outfile"
	fi

done