#!/bin/bash

	# ================================================================================
	# Program:	extract_pkglist_en
	#
	# Purpose:	Extract the <en> description line
	#
	# Author:	old giza
	#
	# Date:		2018.10.14
	#
	#			This can probably be done better with awk or the like.
	#			But it serves the purpose now.
	# ================================================================================

if [ -z "$1" ]
then	echo 'Need tag as argument (do not include < or />'
		exit
fi

tag="$1"
l1tag='<'"$tag"'>'
l3tag='</'"$tag"'>'

outfile="$tag"'.extract'
echo -n > "$outfile"

d='mx-packageinstaller-pkglist'

let filenum=0

for f in $(ls -1 "$d"/*'.pm')
do

	let filenum=filenum+1
	let enfound=0

	while read l
	do
		if [ $enfound -eq 0 ]
		then	[[ "$l" =~ ^.*\<en\>.*\</en\> ]]
				if [ "$?" -eq 0 ]
				then	let enfound=1
						s=${l#*<en>}
						t=${s%</en>*}
				fi
		fi
					
	done < "$f"

	if [ $enfound -eq 0 ]
	then	echo 'file: '"$f"' - did not find expected lines'
	else	echo "$t" >> "$outfile"
	fi

done